name: Hello GitHub Actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: |
           echo "Hello Gagan!"
           echo "Learning GitHub Actions."
           echo "This is my first workflow."
